import type { Product } from "./types";

const LOREM = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
  "Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Duis ac lacus sed turpis sagittis tincidunt. Nullam pulvinar risus non risus hendrerit venenatis.",
  "Curabitur blandit tempus porttitor. Maecenas faucibus mollis interdum. Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue sagittis nec.",
  "Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam porta sem malesuada.",
  "Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.",
  "Aenean lacinia bibendum nulla sed consectetur. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum. Donec sed odio dui aliquam eget bibendum.",
];

export const products: Product[] = [
  {
    id: "p01",
    slug: "voltrax-powerdrive-x7",
    name: "PowerDrive X7",
    brand: "VOLTRAX",
    category: "scule-electrice",
    variant: "drill",
    price: 649,
    oldPrice: 749,
    rating: 4.8,
    reviewsCount: 214,
    sku: "VTX-PD-X7",
    inStock: true,
    badges: ["Bestseller"],
    accent: "bronze",
    shortDescription:
      "Bormașină cu percuție 850W, mandrină metalică 13mm și cuplu variabil pentru beton, lemn și metal.",
    description: [
      "Concepută pentru echipe care lucrează zilnic pe șantier, PowerDrive X7 combină un motor de 850W cu un mecanism de percuție robust, oferind putere constantă indiferent de material.",
      LOREM[0],
      LOREM[2],
    ],
    specs: [
      { label: "Putere motor", value: "850 W" },
      { label: "Mandrină", value: "13 mm, metalică" },
      { label: "Viteză", value: "0–3.000 rpm" },
      { label: "Greutate", value: "2,1 kg" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p02",
    slug: "voltrax-aircut-125",
    name: "AirCut 125",
    brand: "VOLTRAX",
    category: "scule-electrice",
    variant: "grinder",
    price: 589,
    rating: 4.7,
    reviewsCount: 132,
    sku: "VTX-AC-125",
    inStock: true,
    badges: [],
    accent: "steel",
    shortDescription:
      "Polizor unghiular 1200W cu disc de 125mm, protecție anti-recul și mâner antivibrații.",
    description: [
      "AirCut 125 este alegerea potrivită pentru debitare și polizare de precizie, cu o carcasă din aliaj ușor care reduce oboseala brațului pe parcursul unei zile întregi de lucru.",
      LOREM[1],
      LOREM[4],
    ],
    specs: [
      { label: "Putere motor", value: "1.200 W" },
      { label: "Diametru disc", value: "125 mm" },
      { label: "Viteză nominală", value: "11.000 rpm" },
      { label: "Greutate", value: "2,4 kg" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p03",
    slug: "voltrax-truecut-190",
    name: "TrueCut 190",
    brand: "VOLTRAX",
    category: "scule-electrice",
    variant: "saw",
    price: 899,
    rating: 4.9,
    reviewsCount: 76,
    sku: "VTX-TC-190",
    inStock: true,
    badges: ["Nou"],
    accent: "ember",
    shortDescription:
      "Fierăstrău circular 1600W cu ghidaj laser, disc de 190mm și unghi de tăiere reglabil 0–45°.",
    description: [
      "Lansat recent în gama VOLTRAX, TrueCut 190 aduce un ghidaj laser de precizie și o talpă din aluminiu turnat pentru tăieri drepte, repetabile, în orice tip de lemn masiv sau placaj.",
      LOREM[2],
      LOREM[5],
    ],
    specs: [
      { label: "Putere motor", value: "1.600 W" },
      { label: "Diametru disc", value: "190 mm" },
      { label: "Adâncime tăiere", value: "67 mm" },
      { label: "Unghi înclinare", value: "0–45°" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p04",
    slug: "voltrax-flexdriver-18v",
    name: "FlexDriver 18V",
    brand: "VOLTRAX",
    category: "scule-electrice",
    variant: "impactDriver",
    price: 459,
    oldPrice: 519,
    rating: 4.6,
    reviewsCount: 98,
    sku: "VTX-FD-18",
    inStock: true,
    badges: ["Reducere"],
    accent: "bronze",
    shortDescription:
      "Șurubelniță cu impact pe acumulator 18V, cuplu 180Nm și mandrină hexagonală rapidă.",
    description: [
      "Compactă și puternică, FlexDriver 18V susține montaje intensive de structuri din lemn și metal ușor, cu schimbare de accesoriu fără scule.",
      LOREM[3],
      LOREM[0],
    ],
    specs: [
      { label: "Tensiune", value: "18 V" },
      { label: "Cuplu maxim", value: "180 Nm" },
      { label: "Baterie inclusă", value: "2 x 2,0 Ah" },
      { label: "Greutate", value: "1,3 kg" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p05",
    slug: "voltrax-orbitsand-300",
    name: "OrbitSand 300",
    brand: "VOLTRAX",
    category: "scule-electrice",
    variant: "sander",
    price: 379,
    rating: 4.5,
    reviewsCount: 61,
    sku: "VTX-OS-300",
    inStock: true,
    badges: [],
    accent: "steel",
    shortDescription:
      "Șlefuitor orbital 300W cu sistem de extracție praf și talpă de 125mm.",
    description: [
      "Pentru finisaje impecabile pe lemn, chit sau vopsea, OrbitSand 300 oferă o mișcare orbitală fină și un sac de colectare a prafului cu eficiență ridicată.",
      LOREM[4],
      LOREM[1],
    ],
    specs: [
      { label: "Putere motor", value: "300 W" },
      { label: "Talpă", value: "125 mm" },
      { label: "Orbite/min", value: "12.000" },
      { label: "Greutate", value: "1,1 kg" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p06",
    slug: "irongrip-forge-500",
    name: "Forge 500",
    brand: "IRONGRIP",
    category: "scule-de-mana",
    variant: "hammer",
    price: 89,
    rating: 4.9,
    reviewsCount: 341,
    sku: "IGP-FG-500",
    inStock: true,
    badges: ["Bestseller"],
    accent: "bronze",
    shortDescription:
      "Ciocan dulgher forjat dintr-o singură bucată de oțel, cap 500g și mâner ergonomic antișoc.",
    description: [
      "Forjat dintr-o singură piesă de oțel carbon, Forge 500 elimină riscul de desprindere a capului și transferă mai puține vibrații către încheietură.",
      LOREM[5],
      LOREM[2],
    ],
    specs: [
      { label: "Greutate cap", value: "500 g" },
      { label: "Material", value: "Oțel carbon forjat" },
      { label: "Mâner", value: "Fibră de sticlă + cauciuc" },
      { label: "Lungime", value: "330 mm" },
      { label: "Garanție", value: "Garanție pe viață" },
    ],
  },
  {
    id: "p07",
    slug: "irongrip-torqueset-24",
    name: "TorqueSet 24",
    brand: "IRONGRIP",
    category: "scule-de-mana",
    variant: "wrench",
    price: 349,
    rating: 4.8,
    reviewsCount: 156,
    sku: "IGP-TS-24",
    inStock: true,
    badges: ["Bestseller"],
    accent: "steel",
    shortDescription:
      "Trusă chei tubulare 24 piese, crom-vanadiu, cu cutie rigidă de transport.",
    description: [
      "O trusă completă pentru montaj și întreținere, cu capete tubulare cromate rezistente la coroziune și clichet cu mecanism fin de 72 de dinți.",
      LOREM[0],
      LOREM[3],
    ],
    specs: [
      { label: "Piese incluse", value: "24" },
      { label: "Material", value: "Crom-vanadiu" },
      { label: "Interval", value: "8–24 mm" },
      { label: "Clichet", value: "72 dinți" },
      { label: "Garanție", value: "5 ani" },
    ],
  },
  {
    id: "p08",
    slug: "irongrip-griplock",
    name: "GripLock",
    brand: "IRONGRIP",
    category: "scule-de-mana",
    variant: "pliers",
    price: 129,
    rating: 4.6,
    reviewsCount: 88,
    sku: "IGP-GL-250",
    inStock: true,
    badges: [],
    accent: "ember",
    shortDescription:
      "Clește reglabil profesional 250mm cu fălci autoblocante și acoperire anti-alunecare.",
    description: [
      "Mecanismul autoblocant menține presiunea constantă pe piesă, iar fălcile canelate oferă priză sigură pe suprafețe rotunde sau plate.",
      LOREM[1],
      LOREM[4],
    ],
    specs: [
      { label: "Lungime", value: "250 mm" },
      { label: "Deschidere maximă", value: "42 mm" },
      { label: "Material", value: "Oțel forjat crom-molibden" },
      { label: "Mâner", value: "Bi-material antiderapant" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p09",
    slug: "irongrip-clawbar-60",
    name: "ClawBar 60",
    brand: "IRONGRIP",
    category: "scule-de-mana",
    variant: "prybar",
    price: 149,
    rating: 4.7,
    reviewsCount: 54,
    sku: "IGP-CB-600",
    inStock: true,
    badges: [],
    accent: "bronze",
    shortDescription:
      "Rangă multifuncțională 600mm cu cap de smulgere și corp hexagonal pentru priză fermă.",
    description: [
      "Utilă la demolări controlate și demontări, ClawBar 60 combină un braț lung pentru efect de pârghie cu un vârf plat pentru desprinderea materialelor fine.",
      LOREM[2],
      LOREM[5],
    ],
    specs: [
      { label: "Lungime", value: "600 mm" },
      { label: "Material", value: "Oțel aliat călit" },
      { label: "Finisaj", value: "Fosfatat, anti-coroziune" },
      { label: "Greutate", value: "0,9 kg" },
      { label: "Garanție", value: "5 ani" },
    ],
  },
  {
    id: "p10",
    slug: "precia-laserline-30",
    name: "LaserLine 30",
    brand: "PRECIA",
    category: "masurare-nivelare",
    variant: "laser",
    price: 499,
    rating: 4.8,
    reviewsCount: 112,
    sku: "PRC-LL-30",
    inStock: true,
    badges: ["Nou"],
    accent: "steel",
    shortDescription:
      "Telemetru laser 30m cu precizie ±1,5mm, memorie de măsurători și calcul automat de suprafață.",
    description: [
      "LaserLine 30 înlocuiește ruleta clasică pentru măsurători rapide de distanță, suprafață și volum, direct pe ecranul retroiluminat.",
      LOREM[3],
      LOREM[0],
    ],
    specs: [
      { label: "Rază măsurare", value: "0,05–30 m" },
      { label: "Precizie", value: "± 1,5 mm" },
      { label: "Clasă laser", value: "Clasa 2" },
      { label: "Alimentare", value: "2 x baterii AAA" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p11",
    slug: "precia-truelevel-60",
    name: "TrueLevel 60",
    brand: "PRECIA",
    category: "masurare-nivelare",
    variant: "level",
    price: 219,
    rating: 4.9,
    reviewsCount: 143,
    sku: "PRC-TL-60",
    inStock: true,
    badges: [],
    accent: "bronze",
    shortDescription:
      "Nivelă cu bulă din aluminiu extrudat, 60cm, cu 3 fiole de precizie 0,5mm/m.",
    description: [
      "Profilul din aluminiu cu nervuri de rigidizare menține liniaritatea corpului chiar și după utilizare intensă pe șantier.",
      LOREM[4],
      LOREM[1],
    ],
    specs: [
      { label: "Lungime", value: "600 mm" },
      { label: "Precizie fiole", value: "0,5 mm/m" },
      { label: "Material", value: "Aluminiu extrudat" },
      { label: "Rezistență", value: "IP54" },
      { label: "Garanție", value: "10 ani" },
    ],
  },
  {
    id: "p12",
    slug: "precia-tapemaster-8",
    name: "TapeMaster 8",
    brand: "PRECIA",
    category: "masurare-nivelare",
    variant: "tapeMeasure",
    price: 79,
    rating: 4.7,
    reviewsCount: 201,
    sku: "PRC-TM-8",
    inStock: true,
    badges: [],
    accent: "ember",
    shortDescription:
      "Ruletă profesională 8m, bandă din oțel cu strat anti-uzură și cârlig magnetic.",
    description: [
      "Bandă gradată dublu, lizibilă în orice condiții de lumină, cu blocare fermă și revenire controlată pentru a proteja carcasa.",
      LOREM[5],
      LOREM[2],
    ],
    specs: [
      { label: "Lungime", value: "8 m" },
      { label: "Lățime bandă", value: "25 mm" },
      { label: "Clasă precizie", value: "Clasa II" },
      { label: "Carcasă", value: "ABS cauciucat" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p13",
    slug: "aegis-siteguard",
    name: "SiteGuard",
    brand: "AEGIS",
    category: "echipament-protectie",
    variant: "helmet",
    price: 159,
    rating: 4.8,
    reviewsCount: 167,
    sku: "AGS-SG-01",
    inStock: true,
    badges: [],
    accent: "steel",
    shortDescription:
      "Cască de protecție ventilată, certificată EN 397, cu sistem de reglaj rapid.",
    description: [
      "Carcasa din ABS rezistă la impact și radiații UV, iar căptușeala interioară detașabilă poate fi spălată pentru igienă pe termen lung.",
      LOREM[0],
      LOREM[3],
    ],
    specs: [
      { label: "Certificare", value: "EN 397" },
      { label: "Material", value: "ABS de înaltă densitate" },
      { label: "Ventilație", value: "6 fante reglabile" },
      { label: "Greutate", value: "380 g" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p14",
    slug: "aegis-clearview",
    name: "ClearView",
    brand: "AEGIS",
    category: "echipament-protectie",
    variant: "goggles",
    price: 49,
    rating: 4.6,
    reviewsCount: 92,
    sku: "AGS-CV-02",
    inStock: true,
    badges: [],
    accent: "bronze",
    shortDescription:
      "Ochelari de protecție anti-zgâriere și anti-aburire, certificați EN 166.",
    description: [
      "Lentila din policarbonat filtrează radiațiile UV și oferă un câmp vizual larg, fără distorsiuni pe margini.",
      LOREM[1],
      LOREM[4],
    ],
    specs: [
      { label: "Certificare", value: "EN 166" },
      { label: "Lentilă", value: "Policarbonat, tratament UV" },
      { label: "Tratament", value: "Anti-zgâriere / anti-aburire" },
      { label: "Greutate", value: "28 g" },
      { label: "Garanție", value: "1 an" },
    ],
  },
  {
    id: "p15",
    slug: "aegis-griptech",
    name: "GripTech",
    brand: "AEGIS",
    category: "echipament-protectie",
    variant: "gloves",
    price: 69,
    rating: 4.7,
    reviewsCount: 118,
    sku: "AGS-GT-03",
    inStock: true,
    badges: ["Stoc limitat"],
    accent: "ember",
    shortDescription:
      "Mănuși de lucru cu întărituri pe palmă și degete, rezistente la abraziune.",
    description: [
      "Palma dublu-întărită cu poliuretan menține priza sigură pe unelte umede sau unsuroase, fără a sacrifica sensibilitatea tactilă.",
      LOREM[2],
      LOREM[5],
    ],
    specs: [
      { label: "Certificare", value: "EN 388" },
      { label: "Material", value: "Poliuretan + bumbac" },
      { label: "Mărimi", value: "M – XXL" },
      { label: "Rezistență abraziune", value: "Nivel 4" },
      { label: "Garanție", value: "1 an" },
    ],
  },
  {
    id: "p16",
    slug: "forgeworks-anchorpro-m10",
    name: "AnchorPro M10",
    brand: "FORGEWORKS",
    category: "fixare-prindere",
    variant: "anchor",
    price: 189,
    rating: 4.8,
    reviewsCount: 47,
    sku: "FGW-AP-M10",
    inStock: true,
    badges: [],
    accent: "steel",
    shortDescription:
      "Set 50 ancore mecanice M10 din oțel zincat, pentru fixări structurale în beton.",
    description: [
      "Sistemul de expansiune uniformă distribuie sarcina pe toată lungimea găurii, recomandat pentru console, balustrade și structuri suspendate.",
      LOREM[3],
      LOREM[0],
    ],
    specs: [
      { label: "Diametru", value: "M10" },
      { label: "Piese/set", value: "50" },
      { label: "Material", value: "Oțel zincat" },
      { label: "Sarcină admisă", value: "până la 1.450 kg" },
      { label: "Garanție", value: "5 ani" },
    ],
  },
  {
    id: "p17",
    slug: "forgeworks-clampforce-400",
    name: "ClampForce 400",
    brand: "FORGEWORKS",
    category: "fixare-prindere",
    variant: "clamp",
    price: 99,
    rating: 4.6,
    reviewsCount: 63,
    sku: "FGW-CF-400",
    inStock: true,
    badges: [],
    accent: "bronze",
    shortDescription:
      "Clemă de tâmplărie 400mm cu bară din oțel și strângere rapidă cu o mână.",
    description: [
      "Mecanismul cu declanșator permite reglaj rapid, iar fălcile late din polimer protejează suprafețele finisate în timpul asamblării.",
      LOREM[4],
      LOREM[1],
    ],
    specs: [
      { label: "Deschidere", value: "400 mm" },
      { label: "Forță strângere", value: "140 kg" },
      { label: "Material bară", value: "Oțel tratat termic" },
      { label: "Fălci", value: "Polimer, detașabile" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p18",
    slug: "forgeworks-powergen-3200",
    name: "PowerGen 3200",
    brand: "FORGEWORKS",
    category: "utilaje-santier",
    variant: "generator",
    price: 3499,
    rating: 4.9,
    reviewsCount: 39,
    sku: "FGW-PG-3200",
    inStock: true,
    badges: ["Bestseller"],
    accent: "ember",
    shortDescription:
      "Generator pe benzină 3.2kW cu pornire electrică și rezervor de 15 litri.",
    description: [
      "Proiectat pentru alimentarea sculelor electrice pe șantiere fără acces la rețea, cu un nivel de zgomot redus pentru clasa sa de putere.",
      LOREM[5],
      LOREM[2],
    ],
    specs: [
      { label: "Putere maximă", value: "3.200 W" },
      { label: "Rezervor", value: "15 L" },
      { label: "Autonomie", value: "~8 ore la 50% sarcină" },
      { label: "Pornire", value: "Electrică + manuală" },
      { label: "Garanție", value: "3 ani" },
    ],
  },
  {
    id: "p19",
    slug: "forgeworks-airflow-50",
    name: "AirFlow 50",
    brand: "FORGEWORKS",
    category: "utilaje-santier",
    variant: "compressor",
    price: 1299,
    rating: 4.7,
    reviewsCount: 58,
    sku: "FGW-AF-50",
    inStock: true,
    badges: [],
    accent: "steel",
    shortDescription:
      "Compresor de aer 50L, 2 cilindri, pentru pistoale de vopsit și scule pneumatice.",
    description: [
      "Rezervorul de 50 de litri asigură autonomie ridicată între cicluri de pompare, iar sistemul de dublă filtrare protejează motorul pe termen lung.",
      LOREM[0],
      LOREM[3],
    ],
    specs: [
      { label: "Capacitate rezervor", value: "50 L" },
      { label: "Debit aer", value: "280 L/min" },
      { label: "Presiune maximă", value: "10 bar" },
      { label: "Putere motor", value: "2.200 W" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
  {
    id: "p20",
    slug: "forgeworks-mixmaster-140",
    name: "MixMaster 140",
    brand: "FORGEWORKS",
    category: "utilaje-santier",
    variant: "mixer",
    price: 2199,
    rating: 4.8,
    reviewsCount: 44,
    sku: "FGW-MM-140",
    inStock: true,
    badges: ["Nou"],
    accent: "bronze",
    shortDescription:
      "Mixer de mortar 140L cu tambur basculant și șasiu pe roți pentru mobilitate pe șantier.",
    description: [
      "Tamburul din oțel cu palete elicoidale asigură o omogenizare rapidă a mortarului, betonului ușor sau adezivilor pentru gresie.",
      LOREM[1],
      LOREM[4],
    ],
    specs: [
      { label: "Capacitate tambur", value: "140 L" },
      { label: "Putere motor", value: "650 W" },
      { label: "Turație tambur", value: "28 rpm" },
      { label: "Șasiu", value: "Pe roți, basculant" },
      { label: "Garanție", value: "2 ani" },
    ],
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, count = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, count);
}

export function getFeaturedProducts(count = 8) {
  return products.filter((p) => p.badges.length > 0).slice(0, count);
}
